CREATE TABLE PLAYERS(ID string, FIRSTNAME string, LASTNAME string, FIRSTSEASON int, LASTSEASON int, WEIGHT int, BIRTHDATE date)
SELECT FIRSTNAME, LASTNAME, FIRSTSEASON, LASTSEASON FROM PLAYERS WHERE LASTSEASON-FIRSTSEASON>5
