CREATE TABLE PLAYERS(ID string, FIRSTNAME string, LASTNAME string, FIRSTSEASON int, LASTSEASON int, WEIGHT int, BIRTHDATE date)
SELECT EXPERIENCE, COUNT(ID) FROM (SELECT ID, FIRSTNAME, LASTNAME, (LASTSEASON-FIRSTSEASON) AS EXPERIENCE FROM PLAYERS) GROUP BY EXPERIENCE
