CREATE TABLE PLAYERS(
  ID string, 
  FIRSTNAME string, 
  LASTNAME string, 
  FIRSTSEASON int, 
  LASTSEASON int, 
  WEIGHT int, 
  BIRTHDATE date
);

SELECT P1_FIRSTNAME, P1_LASTNAME, P2_FIRSTNAME, P2_LASTNAME 
FROM (SELECT P1.FIRSTNAME AS P1_FIRSTNAME, 
             P1.LASTNAME AS P1_LASTNAME,
             P2.FIRSTNAME AS P2_FIRSTNAME, 
             P2.LASTNAME AS P2_LASTNAME
      FROM PLAYERS P1, PLAYERS P2
      WHERE P1.ID<>P2.ID) P
WHERE P1_FIRSTSEASON<P2_FIRSTSEASON AND P1_LASTSEASON>P2_LASTSEASON;
